#GET http://localhost:3000/users

POST http://localhost:3000/users
Content-Type: application/json

{
  "nickName": "hugoperez"
}

### ====================================
### CREAR POST - Simple (solo texto)
### ====================================

POST http://localhost:3000/posts
Content-Type: application/json

{
  "nickName": "hugoperez",
  "description": "post con urls",
  "imageUrls": ["https://picsum.photos/800/600?random=17","https://picsum.photos/800/600?random=18"],
  "tags": ["nodejs","java"]
}
